variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - config
  - build
  - install
  - basic-bundles
  - test

before_script:
  - apk --update add git make tar curl

configure:
  stage: config
  script:
    - ./ciao-boot.sh configure --ciao_ppl:enabled=no
  tags:
    - ciao
  artifacts:
    expire_in: 2h
    untracked: true
    paths:
      - build-boot/

build:
  stage: build
  script:
    - ./ciao-boot.sh build --bin core builder ciaodbg
  tags:
    - ciao
  artifacts:
    expire_in: 2h
    untracked: true
    paths:
      - build-boot/
      - build/
  dependencies:
    - configure

install:
  stage: install
  script:
    - ./ciao-boot.sh install
  tags:
    - ciao
  artifacts:
    expire_in: 2h
    untracked: true
    paths:
      - build-boot/
      - build/
  dependencies:
    - build

ciaopp:
  stage: basic-bundles
  script:
    - echo # TODO: artifact too large; prebuilt 3rd party in docker base?
    - echo # apk add m4 autoconf automake libtool # required for PPL build
    - echo # ./ciao-boot.sh configure # --ciao_ppl:enabled=no
    - echo # ./ciao-boot.sh configure --ciao_ppl:enabled=no
    - if [ -x /prebuilt-third-party ]; then mv /prebuilt-third-party third-party; fi # Recover prebuilt third-party from image
    - ./ciao-boot.sh configure
    - ./ciao-boot.sh build --bin # builds all activated bundles
  tags:
    - ciao
  artifacts:
    expire_in: 2h
    untracked: true
    paths:
      - build-boot/
      - build/
  dependencies:
    - install

ciaopp_lite:
  stage: basic-bundles
  script:
    - eval "$(build/bin/ciao-env --sh)" # update PATH, etc.
    - ciao clean ciaopp
    - rm bndls/ciaopp_extra/ACTIVATE
    - ciao rescan-bundles
    - ciao build --bin ciaopp
  tags:
    - ciao
  artifacts:
    expire_in: 2h
    untracked: true
    paths:
      - build-boot/
      - build/
  dependencies:
    - install

incanal_assrts:
  stage: test
  script:
    - apk add bash # add bash for the test scripts
    - eval "$(build/bin/ciao-env --sh)" # update PATH, etc.
    - cd bndls/ciaopp_tests/tests/incanal
    - ./compile.sh
    - ./test_incanal_assrts.sh shfr
  tags:
    - ciao
  dependencies:
    - ciaopp_lite

incanal_lite:
  stage: test
  script:
    - apk add bash # add bash for the test scripts
    - eval "$(build/bin/ciao-env --sh)" # update PATH, etc.
    - cd bndls/ciaopp_tests/tests/incanal
    - ./compile.sh
    - ./test_incanal_mon.sh
    - ./quick_run.sh
  tags:
    - ciao
  dependencies:
    - ciaopp_lite

ciaopp_tests:
  stage: test
  allow_failure: true
  script:
    - if [ -x /prebuilt-third-party ]; then mv /prebuilt-third-party third-party; fi # Recover prebuilt third-party from image
    - eval "$(build/bin/ciao-env --sh)" # update PATH, etc.
    - ciao test ciaopp_extra
  tags:
    - ciao
  dependencies:
    - ciaopp

ciaopp_res_tests:
  stage: test
  allow_failure: true
  script:
    - if [ -x /prebuilt-third-party ]; then mv /prebuilt-third-party third-party; fi # Recover prebuilt third-party from image
    - eval "$(build/bin/ciao-env --sh)" # update PATH, etc.
    - ciao custom_run ciaopp_extra resources_test
  tags:
    - ciao
  dependencies:
    - ciaopp

lpdoc:
  stage: basic-bundles
  script:
    - ./ciao-boot.sh build --bin lpdoc
  tags:
    - ciao
  dependencies:
    - install

bibutils:
  stage: basic-bundles
  script:
    - touch bndls/bibutils/ACTIVATE
    - eval "$(build/bin/ciao-env --sh)" # update PATH, etc.
    - ciao rescan-bundles
    - ciao build --bin bibutils
  tags:
    - ciao
  dependencies:
    - install

jvm_in_ciao:
  stage: basic-bundles
  script:
    - ./ciao-boot.sh build --bin jvm_in_ciao 
  tags:
    - ciao
  dependencies:
    - install

ciao_gui:
  stage: basic-bundles
  script:
    - touch bndls/ciao_gui/ACTIVATE
    - eval "$(build/bin/ciao-env --sh)" # update PATH, etc.
    - ciao rescan-bundles
    - ciao build --bin ciao_gui
  tags:
    - ciao
  dependencies:
    - install

wui:
  stage: basic-bundles
  allow_failure: true
  retry:
    max: 2
    when: script_failure
  script:
    - apk add --update nodejs nodejs-npm
    - npm install -g bower
    - touch bndls/wui/ACTIVATE
    - eval "$(build/bin/ciao-env --sh)" # update PATH, etc.
    - ciao rescan-bundles
    - ciao custom_run wui fetch_externals
    - ciao build --bin wui
    - ciao custom_run wui dist
  tags:
    - ciao
  dependencies:
    - install
  artifacts:
    expire_in: 2h
    untracked: true
    paths:
      - build/
  cache:
    paths:
      - third-party/

catalog_ui:
  stage: test
  allow_failure: true
  script:
    - touch bndls/catalog_ui/ACTIVATE
    - eval "$(build/bin/ciao-env --sh)" # update PATH, etc.
    - ciao rescan-bundles
    - ciao build --bin catalog_ui
  tags:
    - ciao
  dependencies:
    - wui

core_tests:
  stage: test
  script:
    - eval "$(build/bin/ciao-env --sh)" # update PATH, etc.
    - ciao test core
  tags:
    - ciao
  dependencies:
    - install

oc_tests:
  stage: test
  script:
    - apk add bash # add bash (currently required for optim-comp scripts)
    - eval "$(build/bin/ciao-env --sh)" # update PATH, etc.
    - ciao rescan-bundles
    - ciao oc:tests full
  tags:
    - ciao
  dependencies:
    - install

rtchecks_testsuite:
  stage: test
  script:
    - eval "$(build/bin/ciao-env --sh)" # update PATH, etc.
    - cd bndls/testsuite/rtchecks
    - ./test_rtchecks.sh
  allow_failure: true
  tags:
    - ciao

unittest:
  stage: test
  script:
    - eval "$(build/bin/ciao-env --sh)" # update PATH, etc.
    - cd bndls/testsuite/unittest
    - ./run_unittest_tests.pl
  allow_failure: true
  tags:
    - ciao
