language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi
  - if [ $CC == clang ] && [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y llvm-3.4 llvm-3.4-dev; fi
  - if [ $CC == gcc ] && [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y gcc-4.9 g++-4.9; fi
  - if [ $CC == clang ] && [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm35 && brew link --force llvm35; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $CC = gcc ]; then export CC=gcc-4.9; export CXX=g++-4.9; fi # otherwise gcc points to old gcc
  - if [ $TRAVIS_OS_NAME == osx ] && [ $CC = gcc ]; then export CC=gcc-4.9; export CXX=g++-4.9; fi # otherwise gcc points to clang
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install emacs build-essential gcc-4.9-multilib libc6-i386 libc6-dev-i386 g++-4.9-multilib; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install emacs texlive texinfo imagemagick; fi
  - echo "using default emacs" # if [ $TRAVIS_OS_NAME == osx ]; then brew tap railwaycat/emacsmacport; brew install emacs-mac; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew tap railwaycat/emacsmacport; brew install imagemagick; fi
  - EXTRAOPTS=""; if [ $TRAVIS_OS_NAME == osx ]; then EXTRAOPTS="--with-docs=no"; fi
  - CIAOROOT=$TRAVIS_BUILD_DIR

before_script:
  - cd $CIAOROOT; ./ciao-boot.sh boot-build $ARCHOPTS --core:custom_cc=$CC
  - cd $CIAOROOT; CIAOPATH=$CIAOROOT ./ciao-boot.sh fetch github.com/ciao-lang/ciao_emacs
  - cd $CIAOROOT; ./ciao-boot.sh configure --instype=local $ARCHOPTS --core:custom_cc=$CC $EXTRAOPTS

script:
  - cd $CIAOROOT; ./ciao-boot.sh build
  - cd $CIAOROOT; ./ciao-boot.sh install

after_success:
  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then echo "missing deploy"; fi

branches:
  only:
    - master

notifications:
  email: false

env:
  - LANG="en_US.UTF-8" ARCHOPTS=
  - LANG="en_US.UTF-8" ARCHOPTS="--core:m32=yes"

os:
  - linux
  - osx
